/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entities.User.userEntity;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import javax.swing.UIManager;

/**
 *
 * @author marcelovillalobos
 */
public class adminPanelForm extends javax.swing.JFrame {

    /**
     * Creates new form userAuthentication
     */
    private userEntity user;
    
    public adminPanelForm(userEntity user) {
        initComponents();
        centerWindowOnScreen();
        this.user = user;
    }

    public adminPanelForm() {
    }
    
    
    
    //Method to force centering the form
    private void centerWindowOnScreen() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle screenRect = ge.getMaximumWindowBounds();
        int windowWidth = getWidth();
        int windowHeight = getHeight();
        int centerX = (int) (screenRect.getWidth() - windowWidth) / 2;
        int centerY = (int) (screenRect.getHeight() - windowHeight) / 2;
        setLocation(centerX, centerY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdminUsers = new javax.swing.JButton();
        btnCollaboratorsAdmin = new javax.swing.JButton();
        btnCerrarSesión = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 43, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Helvetica Neue", 0, 5)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon("/Users/marcelovillalobos/Documents/GitHub/AQL_Generator/src/main/resources/images/ids logo blanco 1.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(217, 217, 217));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Panel de Administración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        btnAdminUsers.setBackground(new java.awt.Color(217, 217, 217));
        btnAdminUsers.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btnAdminUsers.setForeground(new java.awt.Color(43, 43, 43));
        btnAdminUsers.setText("Administrar Usuarios");
        btnAdminUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 490, 70));

        btnCollaboratorsAdmin.setBackground(new java.awt.Color(217, 217, 217));
        btnCollaboratorsAdmin.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btnCollaboratorsAdmin.setForeground(new java.awt.Color(43, 43, 43));
        btnCollaboratorsAdmin.setText("Administrar Colaboradores");
        btnCollaboratorsAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCollaboratorsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollaboratorsAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnCollaboratorsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 490, 70));

        btnCerrarSesión.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesión.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCerrarSesión.setForeground(new java.awt.Color(217, 217, 217));
        btnCerrarSesión.setText("Volver a Inicio");
        btnCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesiónActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollaboratorsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollaboratorsAdminActionPerformed

        
       
        adminCollaboratorsForm adminCollaboratorsForm = new adminCollaboratorsForm(user);
        this.dispose();
        adminCollaboratorsForm.setVisible(true);

    }//GEN-LAST:event_btnCollaboratorsAdminActionPerformed

    private void btnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesiónActionPerformed
        this.dispose();
        homeForm homeForm = new homeForm(user);
        homeForm.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesiónActionPerformed

    private void btnAdminUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUsersActionPerformed

        adminUsersForm adminUsersForm = new adminUsersForm(user);
        this.dispose();
        adminUsersForm.setVisible(true);
    }//GEN-LAST:event_btnAdminUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* Set the FlatLaf look and feel */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf"); // or FlatDarkLaf for dark theme

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPanelForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPanelForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPanelForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPanelForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPanelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminUsers;
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.JButton btnCollaboratorsAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
