/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controller.collaboratorController;
import Controller.userController;
import Interfaces.collaboratorsEventsListener;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author marcelovillalobos
 */
public class agregarColaboradorForm extends javax.swing.JFrame {

    /**
     * Creates new form userAuthentication
     */
    private JTextField[] fields;
    private collaboratorsEventsListener eventsListener;
    

    public agregarColaboradorForm(adminCollaboratorsForm adminCollaboratorsForm) {
        initComponents();
        centerWindowOnScreen();
        populateComboBox();
        this.eventsListener = adminCollaboratorsForm;

        fields = new JTextField[]{
           txtName
        };
        
        

        agregarListenersATextFields(fields);
        agregarListenerAComboBox(CmbBoxType);
    }

    public agregarColaboradorForm() {
    }
    
    

    //Method to force centering the form
    private void centerWindowOnScreen() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle screenRect = ge.getMaximumWindowBounds();
        int windowWidth = getWidth();
        int windowHeight = getHeight();
        int centerX = (int) (screenRect.getWidth() - windowWidth) / 2;
        int centerY = (int) (screenRect.getHeight() - windowHeight) / 2;
        setLocation(centerX, centerY);
    }

    private void populateComboBox() {
        CmbBoxType.addItem("Seleccione un tipo");
        CmbBoxType.addItem("Collaborator");
        CmbBoxType.addItem("Reviewer");
    }

    // Método para añadir listeners a los campos de texto
    private void agregarListenersATextFields(JTextField[] fields) {
        for (JTextField field : fields) {
            field.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    actualizarBotones();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    actualizarBotones();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    actualizarBotones();
                }
            });
        }
    }

// Método para añadir un listener al JComboBox
    private void agregarListenerAComboBox(JComboBox<String> comboBox) {
        comboBox.addActionListener(e -> actualizarBotones());
    }

// Método para actualizar el estado de los botones
    private void actualizarBotones() {
        boolean hayTexto = false;
        boolean todosLlenos = true;

        // Verificar cada campo de texto
        for (JTextField field : fields) {
            if (field.getText().isEmpty()) {
                todosLlenos = false; // Si algún campo está vacío
            } else {
                hayTexto = true; // Si al menos un campo tiene texto
            }
        }

        // Validar el ComboBox (debe tener un valor distinto al índice 0)
        boolean comboBoxSeleccionado = CmbBoxType.getSelectedIndex() != 0;

        // Ajustar las condiciones de validación con el ComboBox
        todosLlenos = todosLlenos && comboBoxSeleccionado;
        hayTexto = hayTexto || comboBoxSeleccionado; // Si el ComboBox es distinto del default, cuenta como texto ingresado

        // Habilitar o deshabilitar los botones según el estado de los campos
        btnVaciarCampos.setEnabled(hayTexto);
        btnAgregar.setEnabled(todosLlenos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblNombreColaborador = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSelectedUser1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVaciarCampos = new javax.swing.JButton();
        lblClientCode1 = new javax.swing.JLabel();
        CmbBoxType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 43, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Helvetica Neue", 0, 5)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon("/Users/marcelovillalobos/Documents/GitHub/AQL_Generator/src/main/resources/images/ids logo blanco 1.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        lblNombreColaborador.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        lblNombreColaborador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreColaborador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreColaborador.setText("Nombre del Colaborador");
        jPanel1.add(lblNombreColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 440, 40));

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setFont(new java.awt.Font("Raleway", 0, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 440, 45));

        lblSelectedUser1.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        lblSelectedUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectedUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedUser1.setText("Agregar Colaborador");
        jPanel1.add(lblSelectedUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 390, 50));

        btnCerrar.setBackground(new java.awt.Color(255, 51, 0));
        btnCerrar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 40, 40));

        btnAgregar.setBackground(new java.awt.Color(93, 186, 71));
        btnAgregar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(43, 43, 43));
        btnAgregar.setText("Agregar Colaborador");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 190, 60));

        btnVaciarCampos.setBackground(new java.awt.Color(204, 204, 204));
        btnVaciarCampos.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnVaciarCampos.setForeground(new java.awt.Color(43, 43, 43));
        btnVaciarCampos.setText("Vaciar Campos");
        btnVaciarCampos.setBorder(null);
        btnVaciarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaciarCampos.setEnabled(false);
        btnVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnVaciarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 190, 60));

        lblClientCode1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        lblClientCode1.setForeground(new java.awt.Color(255, 255, 255));
        lblClientCode1.setText("Tipo");
        jPanel1.add(lblClientCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 440, 40));

        CmbBoxType.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        CmbBoxType.setToolTipText("");
        CmbBoxType.setBorder(null);
        CmbBoxType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmbBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBoxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(CmbBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 440, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            String username = txtName.getText().trim();
            
            String role = (CmbBoxType.getSelectedItem() != null) ? CmbBoxType.getSelectedItem().toString() : "";

            // Validación básica antes de proceder
            if (username.isEmpty()  || role.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            collaboratorController controller = new collaboratorController();
            controller.createCollaborator(username,role);
            eventsListener.onCollaboratorAdded();

            JOptionPane.showMessageDialog(null, "Usuario creado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error: Uno de los elementos no está inicializado correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado al crear el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCamposActionPerformed

        txtName.setText("");
        
        CmbBoxType.setSelectedIndex(0);

    }//GEN-LAST:event_btnVaciarCamposActionPerformed

    private void CmbBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBoxTypeActionPerformed

    }//GEN-LAST:event_CmbBoxTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* Set the FlatLaf look and feel */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf"); // or FlatDarkLaf for dark theme

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarColaboradorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarColaboradorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarColaboradorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarColaboradorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarColaboradorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbBoxType;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVaciarCampos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClientCode1;
    private javax.swing.JLabel lblNombreColaborador;
    private javax.swing.JLabel lblSelectedUser1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
