/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entities.User.userEntity;
import documentData.dataDocumento;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import javax.swing.UIManager;

/**
 *
 * @author marcelovillalobos
 */
public class homeForm extends javax.swing.JFrame {

    /**
     * Creates new form userAuthentication
     */
    
    private userEntity user;
    
    public homeForm(userEntity user) {
        
        initComponents();
        centerWindowOnScreen();
        
        this.user = user;
        btnAdminPanel.setVisible(isAdmin());
        
        lblBienvenido.setText(lblBienvenido.getText() + " " + user.getNameUser());
        
    }

    public homeForm() {
    }
    
    private boolean isAdmin(){
        
        return user.getRoleUser().equalsIgnoreCase("admin");
    }
    
    //Method to force centering the form
    private void centerWindowOnScreen() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle screenRect = ge.getMaximumWindowBounds();
        int windowWidth = getWidth();
        int windowHeight = getHeight();
        int centerX = (int) (screenRect.getWidth() - windowWidth) / 2;
        int centerY = (int) (screenRect.getHeight() - windowHeight) / 2;
        setLocation(centerX, centerY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDocDespacho = new javax.swing.JButton();
        btnDocRecepcion = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        btnAdminPanel = new javax.swing.JButton();
        btnCerrarSesión = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 43, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Helvetica Neue", 0, 5)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon("/Users/marcelovillalobos/Documents/GitHub/AQL_Generator/src/main/resources/images/ids logo blanco 1.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(217, 217, 217));
        jLabel2.setText("Generador AQL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 217, 217));
        jLabel1.setText("¿Qué documento desea generar?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        btnDocDespacho.setBackground(new java.awt.Color(217, 217, 217));
        btnDocDespacho.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btnDocDespacho.setForeground(new java.awt.Color(43, 43, 43));
        btnDocDespacho.setText("Documento de Despacho");
        btnDocDespacho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDespachoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDocDespacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 550, 70));

        btnDocRecepcion.setBackground(new java.awt.Color(217, 217, 217));
        btnDocRecepcion.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        btnDocRecepcion.setForeground(new java.awt.Color(43, 43, 43));
        btnDocRecepcion.setText("Documento de Recepción");
        btnDocRecepcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocRecepcionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDocRecepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 550, 70));

        lblBienvenido.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(217, 217, 217));
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("Bienvenido/a:");
        jPanel1.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        btnAdminPanel.setBackground(new java.awt.Color(217, 217, 217));
        btnAdminPanel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAdminPanel.setForeground(new java.awt.Color(43, 43, 43));
        btnAdminPanel.setText("Panel Administrador");
        btnAdminPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminPanelActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, 220, 50));

        btnCerrarSesión.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesión.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCerrarSesión.setForeground(new java.awt.Color(217, 217, 217));
        btnCerrarSesión.setText("Cerrar Sesión");
        btnCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesiónActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesiónActionPerformed
        this.dispose();
        userAuthenticationForm userAuthenticationForm = new userAuthenticationForm();
        userAuthenticationForm.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesiónActionPerformed

    private void btnDocRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocRecepcionActionPerformed
        String tipoDocumento = "Recepción";
        dataDocumento documento = new dataDocumento();
        dataDocumentoForm dataDocumentoForm = new dataDocumentoForm(tipoDocumento, null);
        this.dispose();
        dataDocumentoForm.setVisible(true);
        
        
    }//GEN-LAST:event_btnDocRecepcionActionPerformed

    private void btnDocDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDespachoActionPerformed
        
        
        String tipoDocumento = "Despacho";
        //dataDocumento documento = new dataDocumento();
        dataDocumentoForm dataDocumentoForm = new dataDocumentoForm(tipoDocumento, null);
        this.dispose();
        dataDocumentoForm.setVisible(true);
        
    }//GEN-LAST:event_btnDocDespachoActionPerformed

    private void btnAdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPanelActionPerformed
        adminPanelForm adminPanelForm = new adminPanelForm(user);
        this.dispose();
        adminPanelForm.setVisible(true);
    }//GEN-LAST:event_btnAdminPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* Set the FlatLaf look and feel */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf"); // or FlatDarkLaf for dark theme

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminPanel;
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.JButton btnDocDespacho;
    private javax.swing.JButton btnDocRecepcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
